name: Coba Workflows

on:
  push:
    branches: ["main"]

jobs:
  job_one:
    name: coba deploy
    runs-on: ubuntu-latest
    steps:
      - name: coba ssh connection
        uses: appleboy/ssh-action@master
        with:   
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{secrets.DO_SSHKEY}}
          passphrase: ${{ secrets.DO_PASSPHRASE }}
          script: |
            cd /var/www/nostracode/coba
            sudo git pull origin main
            sudo git status
            service nginx restart