name: Coba Workflows

on:
  push:
    branches: ["main"]

jobs:
  job_one:
    name: coba deploy
    runs-on: ubuntu-latest
    steps:
      - name: coba ssh connection
        uses: appleboy/ssh-action@master
        env: 
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        with:   
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{secrets.DO_SSHKEY}}
          passphrase: ${{ secrets.DO_PASSPHRASE }}
          script: |
            cd /var/www/nostracode/coba
            pwd
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{secrets.DO_SSHKEY}}"
            sudo git pull origin main
            sudo git status
            service nginx restart